const actionTypes = {
  softLoaderOn: 'SOFT_LOADER_ON',
  softLoaderOff: 'SOFT_LOADER_OFF',
  saveProfile: 'SAVE_PROFILE',
  removeProfile: 'REMOVE_PROFILE',
  getCards: 'GET_CARDS',
  addCard: 'ADD_CARD',
  removeCard: 'REMOVE_CARD',
  getHomeData: 'GET_HOME_DATA',
  addFirstLogin: 'ADD_FIRST_LOGIN',
  removeFirstLogin: 'REMOVE_FIRST_LOGIN',
  storeBiometricData: 'SET_BIOMETRIC_DATA',
  enableBiometric: 'ENABLE_BIOMETRIC',
  setServices: 'SET_SERVICES',

  // using
  getProfile: 'GET_PROFILE',
  updateProfile: 'UPDATE_PROFILE',
  loaderOn: 'LOADER_ON',
  loaderOff: 'LOADER_OFF',
  login: 'LOGIN',
  logout: 'LOGOUT',
  getAllProducts: 'GET_ALL_PRODUCTS',
  getBestProducts: 'GET_BEST_PRODUCTS',
  getMostPurchasedProducts: 'GET_MOST_PURCHASED_PRODUCTS',
  productDetail: 'PRODUCT_DETAIL',
  addToCart: 'ADD_TO_CART',
  emptyCart: 'EMPTY_CART',
  removeFromCart: 'REMOVE_FROM_CART',
  updateCart: 'UPDATE_CART',
  getAllOrders: 'GET_ALL_ORDERS',
  getPackges: 'GET_PACKAGES',
  getProductReview: 'GET_PRODUCT_REVIEWS',
  getOrder: 'GET_ORDER',
  getCourseReview: 'GET_COURSE_REVIEW',
  getCourseWishlist: 'GET_COURSE_WISHLIST',
  getProductWishlist: 'GET_PRODUCT_WISHLIST',
  getOrder: 'GET_ORDER',
  getMySubscription: 'GET_MY_SUBSCRIPTION',
};
export default actionTypes;
